### ISSUE TITLE
Playing videos / OS X 10.11

### ISSUE THREAD

**Issue by szymon-wiatr** [zacol/mirexplayer#2]
There is no button to play videos after create list.
Not working in Chrome / Safari / Firefox

There is no errors in Terminal / Chromo console.

![no-player](https://cloud.githubusercontent.com/assets/1669730/11170439/a1213278-8bd4-11e5-91cb-dbf4d1a25ab7.png)

**Comment by zacol** [comment]
Yeah, there's no error because everything is alright. I just forgot mention that there are two routes.

http://localhost:3000/#/player - for server with player (only one user can be the server).
http://localhost:3000/ - for all other users who wants to co-create playlists.

I write some instructions for install and use Mirex Player as soon as possible.

Thank you for testing. You have a pretty good taste in music ;)

**Comment by zacol** [comment]
I just added using section to Readme.
